# Generated by Django 2.0.2 on 2018-04-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=20)),
                ('menu_level', models.IntegerField()),
                ('menu_order', models.IntegerField()),
                ('p_menu_id', models.CharField(max_length=32)),
                ('menu_icon', models.CharField(max_length=50)),
                ('menu_url', models.CharField(max_length=50)),
                ('is_delete', models.IntegerField()),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
